title: The Bored Martian
description: Needed somewhere to store ideas, interests, and experience 

theme: jekyll-theme-minimal

# jekyll-theme-minimal configs
show_downloads: false
google_analytics: 
